### ISSUE TITLE
Compatibility w/ 1.8.3

### ISSUE THREAD

**Issue by workmanw** [cdchris12/UDM-DNS-Fix#3]
Hello I just bought a UDM PRO and it has the latest firmware on it (1.8.3). I tried this and couldn't get it to work. After doing some research and testing, it seems like the it will no longer use the `/etc/hosts` file definitions when answer DNS lookups :(. I was curious if this was a known issue and if there were any suggestions (aside from running my own DNS server on a PI).

**Comment by cdchris12** [comment]
This should be closed with the merge of #5 . I've personally tested against versions `1.8.6` and `1.10.0`. 

Please reopen if this is not the case. :)
